### ISSUE TITLE
Use Android's Sqlite abstraction instead of raw android.database.* classes.

### ISSUE THREAD

**Issue by kevelbreh** [square/sqlbrite#109]
Could there be some investigation and perhaps implementation of a mechanic to allow for switching between Android's default SQLite engine or one issued by [Requery](https://github.com/requery/sqlite-android)?

@JakeWharton have you given this any thought?

**Comment by AlecStrong** [comment]
seems like something worth forking for? It shouldn't require many changes but it would have to depend on requery/sqlite-android which i doubt sqlbrite ever will.

**Comment by JakeWharton** [comment]
A shim was proposed for SQLCipher support already and we rejected it. It's
highly unfortunate Android's APIs aren't abstracted to be reused. Maybe we
should push for an official support library for this? That would be
something we would support then.

**Comment by JakeWharton** [comment]
Vote (not comment) on http://b.android.com/202658. We're going to try to push this issue first.

**Comment by JakeWharton** [comment]
Here's the rejected SQLCipher change for reference: https://github.com/square/sqlbrite/pull/101

**Comment by JakeWharton** [comment]
Waiting for the first-party SQLite abstraction to reach 1.0 before we can depend on it.

**Comment by JakeWharton** [comment]
Can't wait for this. Will have to be a V3.
