### ISSUE TITLE
WAL mode

### ISSUE THREAD

**Issue by mblcdr** [square/sqlbrite#110]
I see that sqlbrite opens transaction using ```beginTransactionWithListener()``` which as you may know starts the transaction in EXCLUSIVE mode.
I was wondering why you don't use ```beginTransactionWithListenerNonExclusive()``` which makes it possible for read operations to be performed concurrently alongside a write.

**Comment by JakeWharton** [comment]
Simply because we've never used that method, I suppose. What are its disadvantages were we to use it all the time instead of doing something like offering an option?

**Comment by mblcdr** [comment]
Enabling non-exclusive operations requires more memory because it keeps multiple connections to the database. Based on this, I think offering it as an option will be better.

**Comment by JakeWharton** [comment]
I really dislike the "non-exclusive" naming, but I guess we're stuck with it. We can expose a `newNonExclusiveTransaction()` method for this.

**Comment by mblcdr** [comment]
We can use ```newImmediateTransaction()``` as ```beginTransactionNonExclusive()``` starts a transaction in IMMEDIATE mode. But I don't know if that's more helpful. The naming is more vague in this one.
I can send a PR for this, however I have no idea how can I write a test to confirm the transaction actually started not acquiring the exclusive lock. Any ideas?

**Comment by JakeWharton** [comment]
Yeah if we used that the naming difference between that and `SQLiteDatabase` concerns me a bit. That and the fact that it's not really clear what "Immediate" means in this context.

As to a test, it would be something like this:
```java
final BriteDatabase db = //...

final CountDownLatch transactionStarted = new CountDownLatch(1);
final CountDownLatch transactionProceed = new CountDownLatch(1);
final CountDownLatch transactionCompleted = new CountDownLatch(1);

new Thread() {
  @Override public void run() {
    Transaction transaction = db.newNonExclusiveTransaction();
    transactionStarted.countDown();
    transactionProceed.await(10, SECONDS);
    transaction.markSuccessful();
    transaction.close();
    transactionCompleted.countDown();
  }
}.start();

assertTrue(transactionStarted.await(10, SECONDS));

// Copy an assertion here from another test that executes a simple query...

transactionProceed.countDown();
assertTrue(transactionCompleted.await(10, SECONDS));
```

**Comment by mblcdr** [comment]
I worked on this yesterday and found out some info.

First,
Write ahead logging is added to SqliteDatabase in API 11. And Sqlbrite min sdk is 9. So how would you handle such case? Should we fallback to normal transaction if SDK_INT is lower than 11 and logging it, or throw an exception? Or leave it to developer with ```TargetApi``` annotation?

Second,
Sqlbrite uses memory database for tests. WAL is only supported on disk databases and must be enabled in ```onConfigure()```. So should we create a whole other test db which uses disk for the test of it?

Third,
I was actually surprised by the result of tests. Both tests (non-exclusive and default) passed, which is in direct contrast to SqliteDatabase documentation in Android docs.

**Comment by JakeWharton** [comment]
> Or leave it to developer with `TargetApi` annotation?

Let's do this. Except we should use `@RequiresApi` instead.

> WAL is only supported on disk databases

Any idea how much changing the existing tests to run on disk adds to their execution time? Be sure to use a `TemporaryFile` JUnit `@Rule` to ensure we get a fresh location for every test.

> Both tests (non-exclusive and default) passed, which is in direct contrast to SqliteDatabase documentation in Android docs.

What API level did you run the tests on? I wonder if older API levels actually made the distinction between the modes but newer ones just always enable it.

**Comment by mblcdr** [comment]
> we should use ```@RequiresApi``` 

Will do.

> Any idea how much changing the existing tests to run on disk adds to their execution time?

Not much. I'm not sure though. Let me check and get back to you with more info.
However I'm not sure if we should put aside the convinience and simplicity of using an in-memory db for a few tests.

> What API level did you run the tests on?

API 19 Emulator.

> I wonder if older API levels actually made the distinction between the modes but newer ones just always enable it.

I don't think that's the case. You can check if WAL is enabled with `isWriteAheadLoggingEnabled()`. Which by default returns `false`. What I think is that maybe there is some other optimization regarding acquiring locks. Maybe normal transaction does not acquire `EXCLUSIVE` lock anymore. I will test on lower APIs and will report back when the results are ready.

**Comment by JakeWharton** [comment]
> However I'm not sure if we should put aside the convinience and simplicity of using an in-memory db for a few tests.

I don't think it's that big of deal. I was just worried it would slow down the tests by 10x or something. Basically 100% of consumers will be using the library with a file-backed DB anyway so it just puts us closer to real usage.

**Comment by iNoles** [comment]
enableWriteAheadLogging does have synchronized block too. There is the open flag for WAL is ENABLE_WRITE_AHEAD_LOGGING (API Level 16).

**Comment by JakeWharton** [comment]
@mblcdr let me know if I can help move this forward in any way. happy to take a partially working PR.

**Comment by mblcdr** [comment]
Sorry for the delay.

> Basically 100% of consumers will be using the library with a file-backed DB anyway

Can't argue with the numbers. :)
For migrating to disk-based DB, we need a `TemporarilyFolder` rule applied to all of the tests. I would like to know how would you prefer that to be implemented. A custom suite? Adding the rule to all of test files? Or using some black magic, like extending a base test?

I also tested on other APIs, and the results were the same. Turns out SQLite version hasn't changed a lot during the course of Android updates.
However, I don't see any harm including non-exclusive method. Just to be complaint to SQLiteDatabase APIs.

P.S: PR's coming up in a day or two.

**Comment by JakeWharton** [comment]
> all of the tests

Isn't there only `BriteDatabaseTest`?

**Comment by mblcdr** [comment]
> Isn't there only BriteDatabaseTest?

Also a `QueryTest`.

**Comment by JakeWharton** [comment]
That one can stay the same because it's really just testing the operators.
In fact, we could actually switch it to use MatrixCursor and skip the whole
DB if we wanted...

**Comment by mblcdr** [comment]
Ok, thanks for the info.
I will send a PR, and we can continue with some actual code.

**Comment by JakeWharton** [comment]
So I just realized the title of this issue was "WAL mode" but the description and PR are for non-exclusive transactions which aren't the same thing.

WAL, or write-ahead logging, is an alternative to traditional journaling. Non-exclusive affects the locking behavior between database connections.

Is non-exclusive what you really were after, or was it write-ahead logging (which looks like it's just a `PRAGMA` to enable)?

**Comment by mblcdr** [comment]
Well, I was looking for a way to use WAL. In the documentation of SQLiteDatabase, in the [description of WAL](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()), it is stated that:

> `boolean enableWriteAheadLogging ()`
This method enables parallel execution of queries from multiple threads on the same database. It does this by opening multiple connections to the database and using a different database connection for each query. The database journal mode is also changed to enable writes to proceed concurrently with reads.

Which follows:

> Writers should use `beginTransactionNonExclusive()` or `beginTransactionWithListenerNonExclusive(SQLiteTransactionListener)` to start a transaction. Non-exclusive mode allows database file to be in readable by other threads executing queries.

Enabling WAL as you said is just a `PRAGMA` to enable, however using those transaction methods required some changes which I sent as a PR.
