### ISSUE TITLE
Insertion using SqlBrite

### ISSUE THREAD

**Issue by kushalsethi** [square/sqlbrite#114]
Can someone please explain the way for how to insert data into the database using the SqlBrite?
I am not getting the exact way from where I should start.

Thanks!

**Comment by JakeWharton** [comment]
The API is exactly the same as `SQLiteDatabase`. You call the `insert` method with the table name and a `ContentValues` instance containing column/value pairs. Transactions are a little different, but there's an example in the README and Javadoc on the `newTransaction()` method as well.

**Comment by kushalsethi** [comment]
Hi,
I am referring README for insertion. I am not able to return the content values from the method just like what's given in addCustomer method of the README. This method returns Observable<Long>.
Please help me.
Thanks! :)
