### ISSUE TITLE
Insertion using SqlBrite

### ISSUE THREAD

**Issue by kushalsethi** [square/sqlbrite#115]
Hi @JakeWharton ,
I am referring README for insertion. I am not able to return the content values from the method just like what's given in addCustomer method of the README. This method returns Observable.
Please help  me.
Thanks! :)

**Comment by AlecStrong** [comment]
There is no `addCustomer` method in the README, I'm not sure what you're referring to. The insertion is done exactly the same as with `SQLiteDatabase`, so if you are looking for a how-to I'd recommend checking out [google's documentation](https://developer.android.com/training/basics/data-storage/databases.html#WriteDbRow). Where google's documentation uses a `SQLiteDatabase` you would instead use a `BriteDatabase`.
