### ISSUE TITLE
Problem with "toList()" operator

### ISSUE THREAD

**Issue by akobylianskyi** [square/sqlbrite#118]
I ran into a problem related to using of operator "toList". I understand that onCompleted is not called as streams always remain open so that changes to the data can be propagated to all subscribers. But what I can do to transform my stream to list of items and remain stream open?

**Comment by AlecStrong** [comment]
you'll either want to use the `mapToList` function on the returned stream, or the `asRows` function on the emitted query. 

You can see an example of `mapToList` here: https://github.com/square/sqlbrite/blob/master/sample/src/main/java/com/example/sqlbrite/todo/ui/ListsFragment.java#L111

**Comment by akobylianskyi** [comment]
Sorry, I have provided you not all required information. I am using mapToList function after createQuery but after that I do following:

**Comment by AlecStrong** [comment]
oh yea you want the `asRows` function. So this:

```
database.createQuery(Item.TABLE_NAME, Item.QUERY)
  .flatMap(query -> query.asRows(Item.MAPPER::MAP))
```

the type of that stream will be `Observable<Item>`

**Comment by akobylianskyi** [comment]
I have created the question on stackoverflow: [(http://stackoverflow.com/questions/37925020/combine-two-observables-without-using-tolist-because-of-sqlbrite-under-the-hoo)]
Thanks for response.
