### ISSUE TITLE
Problem with "concat()" operator

### ISSUE THREAD

**Issue by amolkov** [square/sqlbrite#123]
I'm not able to use Observable.concat() with SqlBrite to concatenate few observables. So, after SqlBrite returned some result the other observables is not called.
For example, in this case I always get null from localSource and noting else:
```
return Observable.concat(localSource, remoteSource).first();
```
In this case localSource returns null (since there is no data, e.g. first application launch) and after that code execution stops in first filter check:
```
return Observable.concat(localSource, remoteSource)
        .filter(new Func1<Item, Boolean>() {
            @Override
            public Boolean call(Item item) {
                return item!= null;
            }
        });
```
For fetch data from db using next code:
```
@Override
public Observable<Item> get(String id) {
    //creating sql query

    return databaseHelper.createQuery(ItemEntry.TABLE_NAME, sqlQuery, id)
        .mapToOneOrDefault(mapperFunction, null);
}
```

**Comment by artem-zinnatullin** [comment]
Your function Observable<Item> get() returns endless Observable because
mapToOneOrDefault does not complete Observable on its own and reacts to
updates of the db. You need to limit emission of this Observable because
operator concat waits for onCompleted event.

**Comment by amolkov** [comment]
Got it, thank you!

**Comment by barykaed** [comment]
Beginner here, I'm using a mapToList operator in a similar situation. and facing the exact same issue. Can you suggest me how do i finish this endless observable? I'm trying to concat this observable with another from  retrofit.

Thanks in advance! @artem-zinnatullin  @amolkov

**Comment by artem-zinnatullin** [comment]
You can use filtering operators
http://reactivex.io/documentation/operators.html like take(n) to limit
emission of the Observable.

**Comment by barykaed** [comment]
Got it... Thanks once again @artem-zinnatullin

**Comment by fisache** [comment]
@barykaed , same issue, me too. Is there the way to obtain size from mapToList operator or using another method?
I tried to obtain size with count(), map() etc.. however all things to try weren't reached to onNext() when subscribe.
Another way is using concat()
```java
return concat(localSource, localSource).first();
```
it is work, however so weird code.. 
If you solved using take or any methods, give me some helps. Thx 👍 👍
