### ISSUE TITLE
Query.mapToOne and take(1) on an originally empty table doesn't get any item emissions

### ISSUE THREAD

**Issue by jinatonic** [square/sqlbrite#124]
When a table is originally empty, I would expect `Query.mapToOne` to emit nothing until the table gets populated. So if I want to create a sqlbrite observable that listens to the table until the table gets populated with the expected value, I would do something like this:

`db.createQuery(...).mapToOne(...).take(1).subscribe(...);`

However, it seems that `take(1)` somehow causes sqlbrite to stop listening to the table triggers despite the fact that no items have been emitted from the upstream observable. If I switch the above code to use `take(2)` or `mapToOneOrDefault(...).take(2)`, then I would properly get a ping downstream when the table gets populated.

I can't find a reliable repro step with just rx streams which makes me think that it's something that sqlbrite is doing.

I am also able to reproduce this in the sample app provided here. Simply add a dummy table `tmp`, and run the following code in `ListFragment#onResume`.

> 

    db.delete("tmp", null);
    db.createQuery("tmp", "SELECT * FROM tmp")
            .mapToOne(new Func1<Cursor, Object>() {
              @Override
              public Object call(Cursor cursor) {
                return new Object();
              }
            })
            .doOnNext(new Action1<Object>() {
              @Override
              public void call(Object o) {
                System.out.println("Received item");
              }
            })
            .take(1)
            .subscribe();

    Observable.timer(5, TimeUnit.SECONDS)
            .subscribe(new Action1<Long>() {
              @Override
              public void call(Long aLong) {
                final ContentValues cvs = new ContentValues();
                cvs.put("text", "TEXT");
                db.insert("tmp", cvs);
              }
            });

What happens in the above code is that if I leave it as `take(1)`, then I never get the `Received item` print. However, if I change it to `take(2)`, I properly get the `Received item` callback.

**Comment by JakeWharton** [comment]
Yep, as I thought on Slack this is indeed backpressure-related. We need to track request counts through our custom operator and re-request when we swallow an event.
