### ISSUE TITLE
General query about Observable creation

### ISSUE THREAD

**Issue by masterlittle** [square/sqlbrite#131]
Hi, I was just going through the source code of SQLBrite and I saw it using Observable.create() to wrap Observables. Is that a decision taken by necessity or can we use .fromCallable() instead of create() to wrap over because I am always encountering statements which discourage the use of create().

**Comment by JakeWharton** [comment]
As a library we can only use stable APIs. Beyond that, though, we have done
extensive testing to ensure our Observable adheres to the contract required
by create().

In a general case, you should avoid create() at all costs unless you
really, really know what you're doing.
