### ISSUE TITLE
applyBatch()/ bulk insert support

### ISSUE THREAD

**Issue by rahulmcs** [square/sqlbrite#132]
Unless I am missing something, BriteContentResolver does not seem to support applyBatch for bulk inserts. What is the recommended strategy for bulk inserts/updates using SQLBrite?

**Comment by AlecStrong** [comment]
`BriteContentResolver` functions properly with the original `ContentResolver`, so performing mutating operations (like `applyBatch`) will emit updates to the observables you get from the `BriteContentResolver`. 

Only wrap a `ContentResolver` if you want a reactive version of `registerContentObserver`

**Comment by rahulmcs** [comment]
Ok, now clarified that SQLBrite is not an all purpose reactive wrapper around the ContentResolver but only around those bits that deal with updates to the underlying data set. I originally assumed that SQLBrite will also provide an observable interface for applyBatch but clearly that is not the case.
