### ISSUE TITLE
Question: How to properly create Observable of Parent/child relationship with contentResolver 

### ISSUE THREAD

**Issue by chriswiesner** [square/sqlbrite#133]
As you already mentioned in #102 we should avoid having this parent/child object construction. but as i'm using a contentresolver i cannot create a joined query here.

therefore my current approach looks like that:
```
private Observable<State> getLatestStateObservable() {
	// ... setup query params
	return contentResolver.createQuery(STATE_URI, ...).mapToOne(State::fromCursor);
}

private Observable<Item> getLatestItem(State state) {
	// ... use State.id in params

	return contentResolver.createQuery(ITEM_URI, ...).mapToOne(Item::fromCursor);
}

subscriptions.add(statusObservable.observeOn(...).subscribe(state -> {
	subscriptions.add(getLatestItem(state)).observeOn(...).subscribe(item -> {
		// do sth
	});
});
```

how could i use those observables on several places? goal would be access those observables from different Presenters. do i have to subscribe in every presenter like the above lines to get the latest Item?

**Comment by AlecStrong** [comment]
if you're only using `mapToOne` and only care about having an `Item` then a switchmap should work:

```java
private Observable<Item> getLatestItem() {
  return getLatestStateObservable().
    .switchMap(state -> getLatestItem(state));
}
```

**Comment by JakeWharton** [comment]
Let us know if that answer doesn't sufficiently cover your use case.

**Comment by chriswiesner** [comment]
thx, that works!
question is, if I have another query that depends on the state query. with that solution i'd create a an additional state query observable. could i reuse an existing one?
furthermore, as already mentioned in my first post. if i have multiple presenters which need on those observables, is there a proper way to "reuse" them without each presenter creating a different observable?

**Comment by AlecStrong** [comment]
We use [RxReplayingShare](https://github.com/JakeWharton/RxReplayingShare) to accomplish that goal. You would have a field somewhere like

```java
Observable<Item> latestItem = getLatestStateObservable()
  .switchMap(state -> getLatestItem(state))
  .compose(RxReplayingShare.instance());
```

and then expose that field to your presenters.

For your first question (multiple queries using the same state query) depending on when these queries are active RxReplayingShare could help but you probably want to look into [ConnectableObservables](https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators)

**Comment by chriswiesner** [comment]
thx again, i'll have a look at that.
