### ISSUE TITLE
Question/Issue on createQuery and triggers

### ISSUE THREAD

**Issue by kkovach** [square/sqlbrite#134]
I've created an Observable similar to 

```
db.createQuery(Widget.TABLE, Widget.QUERY_STATUS_BY_ID_COLOR_SHAPE, args)
.mapToOneOrDefault(Widget.DOWNLOAD_STATUS_MAPPER, DownloadStatus.NOT_DOWNLOADED);
```

and updates to Widget.TABLE do not appear to be triggering the query again and unfortunately I do not understand why that is. I've enabled logging and I can see the following...

```
D/SqlBrite(3186): Binding widget view and subscribing to status.
D/SqlBrite(3186): Subscribing to status for Widget 46790, Color blue, Shape circle
D/SqlBrite(3186): QUERY (0ms)
D/SqlBrite(3186):   tables: widgets
D/SqlBrite(3186):   sql: SELECT downloadStatus FROM widgets WHERE id = ? AND color = ? AND shape = ?
D/SqlBrite(3186):   args: [46790, blue, circle]
D/SqlBrite(3186): Binding widget view and subscribing to status.
D/SqlBrite(3186): Subscribing to status for Widget 46790, Color blue, Shape square
D/SqlBrite(3186): QUERY (0ms)
D/SqlBrite(3186):   tables: widgets
D/SqlBrite(3186):   sql: SELECT downloadStatus FROM widgets WHERE id = ? AND color = ? AND shape = ?
D/SqlBrite(3186):   args: [46790, blue, square]
D/SqlBrite(3186): Got updated status DOWNLOADED.
D/SqlBrite(3186): Got updated status DOWNLOADED.
D/SqlBrite(3186): Updating status of 46790 to NOT_DOWNLOADED
D/SqlBrite(3186): UPDATE
D/SqlBrite(3186):   table: widgets
D/SqlBrite(3186):   values: downloadStatus=NOT_DOWNLOADED
D/SqlBrite(3186):   whereClause: id = ?
D/SqlBrite(3186):   whereArgs: [46790]
D/SqlBrite(3186):   conflictAlgorithm: fail
D/SqlBrite(3186): UPDATE affected 2 rows
D/SqlBrite(3186): TRIGGER [widgets]
```

* I've added more logging to check the subscriptions and calls to isUnsubscribed() return false.
* Should I see the QUERY again in the logging if they where still subscribed to?
* The README says "Subscribe to the returned Observable<Query> which will immediately notify with a Query to run. Unlike a traditional rawQuery, updates to the specified table(s) will trigger additional notifications for as long as you remain subscribed to the observable." I don't believe mapToOneOrDefault effects this, does it?

I've exhausted all of my ideas here and any help, hints, or advice on what else to check or look into would be appreciated. Thanks.

**Comment by AlecStrong** [comment]
yea `mapToOneOrDefault` behaves no differently (in terms of triggers). You could add a log in between those first to to be 100% confident it isn't your mapper causing problems:

```java
db.createQuery(Widget.TABLE, Widget.QUERY_STATUS_BY_ID_COLOR_SHAPE, args)
  .doOnNext(query -> Log.d("test", "Triggered"))
  .mapToOneOrDefault(Widget.DOWNLOAD_STATUS_MAPPER, DownloadStatus.NOT_DOWNLOADED);
```

if you're seeing that log it could be that the mapper is crashing and the errors aren't being consumed. If you dont see the log the only other thing I can think of that could be happening is the observable is getting unsubscribed from.

To answer your second question, the query is logged whenever `query.run()` is called, which happens during the `mapToOneOrDefault` operation

**Comment by kkovach** [comment]
Thanks for the help and info @AlecStrong . It appears I've narrowed the issue down to my ignorance of Dagger components and scopes. :-/
