### ISSUE TITLE
Observable gets triggered multiple times in Transaction

### ISSUE THREAD

**Issue by chriswiesner** [square/sqlbrite#135]
On App-Startup i query the db and update a view on result. At the same time i do get new entries from a webservice - those are written in the db with a transaction (i'm using a contenresolver here, so i already have overridden the applyBatch method to use transactions, as it seems, it's not done per default)

```@Override
	public ContentProviderResult[] applyBatch(ArrayList<ContentProviderOperation> operations) {
		...
		db.beginTransaction();
		try {
			for (ContentProviderOperation operation : operations) {
				result[i++] = operation.apply(this, result, i);
			}

			db.setTransactionSuccessful();
		} catch (OperationApplicationException e) {
			Log.d(TAG, "batch failed: " + e.getLocalizedMessage());
		} finally {
			db.endTransaction();
		}

		return result;
	}
```

Problem is, that the observable is triggered for every db action, alltough i perform them inside a transaction.

How do i achieve only one update of the observable?

**Comment by AlecStrong** [comment]
are you using the `ContentProvider` with SqlBrite or the `OpenHelper`

IE do you call `wrapContentProvider` or `wrapDatabaseHelper` ?

**Comment by chriswiesner** [comment]
inserting the new entries is done by a plain ContentProvider/ContentResolver as it's done by a different component in the app (which is rather big) and i didn't adapt all db access to sqlbrite.

i just used the wrapped ContentProvider for the query.

**Comment by AlecStrong** [comment]
gotchya. The wrapped ContentProvider doesn't actually use transactions for notifications at all, it uses android's ContentResolver callbacks to emit data. Internally we just call `registerContentObserver` with the uri you pass into your query. So every time `notifyChange` is called on that uri, a new cursor will be emitted.

My guess is that when you call `operation.apply` it is calling `notifyChange` somewhere which is triggering the sqlbrite stream.

**Comment by chriswiesner** [comment]
according to this http://stackoverflow.com/questions/9801304/android-contentprovider-calls-bursts-of-setnotificationuri-to-cursoradapter-wh?answertab=votes#tab-top notifications should be sent after the transaction completes. not sure though

**Comment by chriswiesner** [comment]
reading further here: http://stackoverflow.com/questions/9801304/android-contentprovider-calls-bursts-of-setnotificationuri-to-cursoradapter-wh?answertab=votes#tab-top

it seems that the transaction just postpones the notifications.

**Comment by AlecStrong** [comment]
there might be something at https://github.com/ReactiveX/RxJava/wiki/Backpressure that could help. Maybe `throttleFirst`?

**Comment by chriswiesner** [comment]
thanks for your quick replies!

`throttleFirst`did work indeed.
but still this is kind of a hacky workaround. how to come up with a trottle threshold? and still the query is run x-times, right?
also you have to add that for every query-observable where "bulk" operations "could" happen.
a handling with the transaction would be nicer imho. but i see that we're limited here, as the contentresolver notifies that often.

**Comment by chriswiesner** [comment]
thanks for your replies.

in the end i customized the notify handling of my Contentprovider in order to avoid timing issues with `throttleFirst`. Also with that, the db-operations will specify the handling of `notify` and my observables don't have to care about bulk operations on their observed tables. 

i think `throttleFirst`  could still be used additionally or in general when the observable's change is causing complex computation.

**Comment by AlecStrong** [comment]
Sounds good! There's probably nothing we can do in `BriteContentResolver` so I'll leave as is.
