### ISSUE TITLE
Request port RxJava 2.0

### ISSUE THREAD

**Issue by rajchithathur** [square/sqlbrite#136]
Hi ,
Thanks for this library 
Any chance support Rxjava 2.0 

Thanks,
Rajesh Rajendiran

**Comment by JakeWharton** [comment]
Yes. All our libraries will be updated eventually.

**Comment by vanniktech** [comment]
Is this being worked on or could I take a stab at it?

**Comment by JakeWharton** [comment]
There won't be any releases of Square libraries with RxJava 2 support until
after its final release.

**Comment by ArazAbishov** [comment]
Is there an approximate date when SqlBrite will be adapted to RxJava 2.0?

**Comment by JakeWharton** [comment]
No

**Comment by ArazAbishov** [comment]
Is this issue open for contributions from community? Or it is something what Square team considers to do?

**Comment by JakeWharton** [comment]
We're probably going to release a 1.0 before conversion. Use the interop
library for now to adapt 1.x into 2.x.

**Comment by jiechic** [comment]
the rxjava 2.0 is release
when will support rxjava 2.0?

**Comment by JakeWharton** [comment]
When we have time. Use the interop library for now.

**Comment by xswapnull** [comment]
@JakeWharton Is there any update on this? We want to start with RxAndroid 2.0.

**Comment by JakeWharton** [comment]
You can use the RxJava 2 interop library for now.

**Comment by xswapnull** [comment]
mDatabaseHelper.createQuery returns rx.Observable and I want it to be io.reactivex.Observable.

Also, sqlbrite has dependancy on RxJava 1.0. Not able to use RxAndroid 2.0 and 1.0 at the same time.

**Comment by iNoles** [comment]
@xswapnull the RxJava 2 interop library allows you to do it.

**Comment by JakeWharton** [comment]
Blocked by https://github.com/JakeWharton/RxBinding/issues/281

**Comment by refaelraz** [comment]
Hi, I saw many closed tasks for RxJava 2 porting, is it possible to use the Rx2 variant  ?

**Comment by ArazAbishov** [comment]
@JakeWharton Are you accepting contributions for porting SQLBrite to RxJava2 at this point?

**Comment by JakeWharton** [comment]
No. I'm working on it.

**Comment by marcinsus** [comment]
@JakeWharton Still do not accept contributions?

**Comment by JakeWharton** [comment]
I have 90% of it done. Just need to find time to finish. It's not that I'm
not accepting contributions it's just that this change has larger
implications that don't allow for an eacy transition.

**Comment by ChenAce** [comment]
JakeWharton,wait you to support rxjava 2.0

**Comment by mynote** [comment]
@JakeWharton, any news about the update? Cant wait for your release in a new project, since it may help alot.

**Comment by aballano** [comment]
@mynote Please read the thread above. If there are new changes they will be posted here.

**Comment by krmao** [comment]
wait and wait ...
