### ISSUE TITLE
How to query multiple condition and mutiple values

### ISSUE THREAD

**Issue by Maxwell6635** [square/sqlbrite#137]
Hi I want to ask how can we use sqlbrite query to query multiple condition with multiple values from a list.
For example : 
SELECT *
FROM example_associates
WHERE example_id IN (value1,value2,...) AND value_id IN (value1,value2,...)

**Comment by JakeWharton** [comment]
That's a SQL question which doesn't have anything to do with SQL Brite
itself. Please ask on a more appropriate forum like StackOverflow.
