### ISSUE TITLE
sometimes query&insert due to deadcycle

### ISSUE THREAD

**Issue by pscj** [square/sqlbrite#151]
The test code is below. Similar to my project code, the insert action may revoke the query code, again and again.

public class MainActivity extends AppCompatActivity {

    private DBHelper mDbhelper;
    private BriteDatabase db;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mDbhelper = new DBHelper(this);
        SqlBrite sqlBrite = SqlBrite.create();
        db = sqlBrite.wrapDatabaseHelper(mDbhelper, Schedulers.io());

        Subscription sub1 = getData("1")
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Action1<SqlBrite.Query>() {
                    @Override
                    public void call(SqlBrite.Query s) {
                        //http request for data

                        //save data
                        insertData();
                    }
                });
        Log.i("test",""+sub1.isUnsubscribed());
    }

    private rx.Observable<SqlBrite.Query> getData(final String str){
        Log.i("test","getdata:"+ str);
        return db.createQuery("message","select * from message");
    }
    private void insertData(){
        Log.i("test","insertdata");
        ContentValues  cv = new ContentValues();
        cv.put("id", "2");
        try{
            db.insert("message",cv );
        } catch (SQLiteConstraintException e) {
            e.printStackTrace();
        }
    }
}

**Comment by JakeWharton** [comment]
There's not a whole lot we can do here. The problem is in your logic, not in the library. You created the loop with no way for it to break except when the `insert` throws an exception. One of these two operations should not happen as the result of the other and which one is up to you.

**Comment by pscj** [comment]
Thank u for you replay. I think my logic is common for app. Please let me describe the app logic.
step 1. check local data,if the data no exists, goto step2.
step2. get data from REST API
step3. save data to local stroage.

**Comment by JakeWharton** [comment]
Your sample is missing the "if data exists" part that would break the cycle.

**Comment by pscj** [comment]
OMG. The sample made mistake, I will fix it. thanks a lot.
