### ISSUE TITLE
The sample can not work.

### ISSUE THREAD

**Issue by ilumer** [square/sqlbrite#152]
`ListsFragment.java` </br>
`void android.widget.ListView.setEmptyView(android.view.View)` on a `null` object reference
device Sony API 23

**Comment by Haoxiqiang** [comment]
I change sample->build.gradle
line 23 annotationProcessor to apt,I think it's a error.
@ilumer try it.

**Comment by JakeWharton** [comment]
@Haoxiqiang it isn't an error.

Without more details we have no way of knowing what's happening in the original report. I can assure you the sample is working locally for us.
