### ISSUE TITLE
BriteDatabase should expose getWriteableDatabase for use with SQLDelight

### ISSUE THREAD

**Issue by burntcookie90** [square/sqlbrite#159]
Currently you have to pass your instance of `SqlLiteOpenHelper` around alongside your `BriteDatabase` in order to use SQLDelight compiled statements with sqlbrite. It would be much nicer to just pass the `BriteDatabase` instance and be able to retrieve the database via `BriteDatabase#getWriteableDatabase`.

**Comment by JakeWharton** [comment]
Send a PR?

**Comment by burntcookie90** [comment]
Aye, probably should have started with that. I'll do it during the day
