### ISSUE TITLE
Use repeatWhen on QueryObservable

### ISSUE THREAD

**Issue by alexbeville** [square/sqlbrite#173]
Hi,

In order to make a cycling synchronisation, I use a repeatWhen on a QueryObservable.

The thing is that QueryObservable use to trigger every subscription when a query identified by the table name is executed (like in example, I mean 
`mDatabaseHelper.createQuery(TABLE_NAME, sql, null).mapToOneOrDefault(MAPPER, null);` where TABLE_NAME is the id)

Using repeatWhen, it seems that it recreates an Observable with a new subscription. I can see in my log that the subscribe method is triggered more than once per cycle.

Is there any advice of how to use repeatWhen with BriteDatabase ? (I was thinking about create a query name from timestamp, but I don't think it's a good practice)

My code : 
```
repository.getSomething()
                    .repeatWhen(new Func1<Observable<? extends Void>, Observable<?>>() {
                        @Override
                        public Observable<?> call(Observable<? extends Void> observable) {
                            return Observable.interval(5, TimeUnit.SECONDS);
                        }
                    })
                    .observeOn(SchedulerProvider.getInstance().ui())
                    .subscribeOn(SchedulerProvider.getInstance().io())
                    .subscribe(new Action1<Integer>() {
                        @Override
                        public void call(Integer aBoolean) {
                            LogUtils.debug("Context", "getSomething() called !");
                        }
                    });
```

**Comment by JakeWharton** [comment]
After re-reading this a few times, it seems like you're asking a general RxJava usage question and not one specific to this library. I would recommend posting to StackOverflow or the RxJava mailing list with your desired effect of re-emitting the last item every 5 seconds if no other item was emitted.
