### ISSUE TITLE
mapToOne and empty result sets

### ISSUE THREAD

**Issue by eliasbagley** [square/sqlbrite#174]
Hi! I'm having a problem with `mapToOne` and `mapToOneOrDefault` using sqlbrite 1.1.1 and interop with RxJava2. 

What I'm trying to do is query for a single object (which may not exist) and do a `blockingFirst()` on a background thread - the problem is that if I use `mapToOne`, then per the documentation "result sets with 0 rows do not emit an item". I can use `mapToOneOrDefault`, which returns my default object when there are no rows in the result set. But checking for the existence of a special default value feels like the wrong way to do this - what I really want is something like a null default value, but it isn't supported in RxJava2.

What is the best approach here to block and get an object that may not exist? Should I be using `mapToList()` and then handle the case when the list is empty, or is there a more idiomatic way?

**Comment by JakeWharton** [comment]
I don't have a good answer.

The null-object pattern is good. I've also filed #186 which would return `Optional<T>` (but only be available on API 24+). You could also write your own version of `mapToOne` which returned a custom wrapper to represent absence.
