### ISSUE TITLE
Can I use SQLBrite in my existing app.

### ISSUE THREAD

**Issue by pareeksumit** [square/sqlbrite#177]
This is not a issue with the library. I wanted to know if I can use sqlbrite with my existign app. I already have a database.

**Comment by aballano** [comment]
@pareeksumit If it's a normal DB or a ContentProvider, yes you can, SQLBrite is just a wrapper around those.

**Comment by pareeksumit** [comment]
Yes mine is a ContentProvider. I want to use SQLBrite + SQLDelight combo for new tables that I am creating. That should be possible right @aballano ?

**Comment by aballano** [comment]
@pareeksumit Yes, you just need to read through the "Usage" part in the Readme or [take a look at the sample](https://github.com/square/sqlbrite/tree/master/sample) in this project.

**Comment by JakeWharton** [comment]
Thanks @aballano

**Comment by pareeksumit** [comment]
Thanks a lot @aballano
