### ISSUE TITLE
[Feature Request] Add conflictAlgorithm parameter to executeInsert() and executeUpdate()

### ISSUE THREAD

**Issue by sockeqwe** [square/sqlbrite#178]
```java
briteDatabase.insert(@NonNull String table, @NonNull ContentValues values,
      @ConflictAlgorithm int conflictAlgorithm)
```  
and 
```java
briteDatabase.update(@NonNull String table, @NonNull ContentValues values,
      @ConflictAlgorithm int conflictAlgorithm, @Nullable String whereClause,
      @Nullable String... whereArgs)
``` 

already support conflict algorithm. However, their counterpart for raw SQL Statements, `executeInsert()` and `executeUpdateDelete()` doesn't support conflict algorithm.

Do you think we should add this? 
I see a strong use case for this `CONFLICT_REPLACE` and SqlDelifght which has deprectaed `Marshaller` in favor of compiled statements.

I would gladly send you a pull request for this.

**Comment by AlecStrong** [comment]
Conflict algorithms are supplied in the SQLite instead of the java layer
for compiled statements

INSERT OR REPLACE INTO ...

**Comment by sockeqwe** [comment]
I see, makes sense.
So we should i.e. write `INSERT OR REPLACE INTO MyTable VALUES (...)`

Alec Strong <notifications@github.com> schrieb am So., 23. Apr. 2017, 15:04:
