### ISSUE TITLE
API 14

### ISSUE THREAD

**Issue by kevelbreh** [square/sqlbrite#18]
Is there a specific reason outlining as to why this library is target towards min SDK level 15 and up?  If not, could I push a change for 14 and up instead?  With 14 being the lowest end of Android 4, it would be easier assumption that this would then run on all versions of Android, 4 and up.

**Comment by AlecStrong** [comment]
As far as I know it's best practise to use 15 instead of 14, there are barely any (if any at all) devices on 14, so there's no real reason to downgrade.

**Comment by kevelbreh** [comment]
There are quite a few in South Africa.  Majority of device owners don't have access to facilities which allow them to perform updates.  Once they have a phone on a specific version, that's it for the lifetime of the phone.

**Comment by hamidp** [comment]
Google does not even report usage for API 14 since it's so low. Do you have any sources of that information for SA?

**Comment by kevelbreh** [comment]
Analytic information for apps I've been involved with which unfortunately I can't share.  If there is no disadvantage to reducing the API level from 15 to 14, then why make a deal of it?

**Comment by JakeWharton** [comment]
Nothing matters less to me. We could probably be API 1. Send a PR?
