### ISSUE TITLE
Request replace operator

### ISSUE THREAD

**Issue by andrev18** [square/sqlbrite#181]
Hello,
Is there any reason why [replace](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#replace(java.lang.String,%20java.lang.String,%20android.content.ContentValues)) operator is missing? It would be useful.
Right now I use the getWritableDatabase() on BriteDatabase object to use the replace method, but I lose the notification feature on table change. Is there a way to force table to reload queries?
Thanks,
Andrei

**Comment by JakeWharton** [comment]
That is a convenience method for `insertWithOnConflict` with a conflict strategy of `CONFLICT_REPLACE` which you can use in this library via the three-argument `insert` method.
