### ISSUE TITLE
Insert or Update functionality (model requirement)

### ISSUE THREAD

**Issue by kevelbreh** [square/sqlbrite#19]
In a current application that I'm writing I need to perform a lot of data synchronization.  To avoid performing a lot of queries to check if items exist, then updating or insert, ideally I would want to use something like [INSERT OR REPLACE](http://stackoverflow.com/questions/418898/sqlite-upsert-not-insert-or-replace/4330694#4330694) and COALESCE on the columns that can be updated.

It would be great if this where to happen in the future to avoid having to query the database a ton of times. I see this being something built into the model builder. If a defined column (by annotation) is editable  (by annotation) after inserting then the builder should add a content item such that the value is something like:

``` java
values.add(COLUMN_NAME, String.format("COALESCE((SELECT %s FROM %S WHERE id = %s), '%s')", 
COLUMN_NAME, TABLE, ID, value);
```

This approach allows us to use the current updating / inserting mechanisms without having to use `execSql(String sql)`.  The ID would need to be set within the builder before calling the method which adds this content value though.

**Comment by JakeWharton** [comment]
We have no plans to add anything in this library for helping build queries/insert/updates or models so I'm going to close.
