### ISSUE TITLE
BriteContentResolver leak canary memory leak

### ISSUE THREAD

**Issue by oksett** [square/sqlbrite#197]
I am searching for my memory leak(attached) i don't know exactly what can cause the problem, even at first sight. Can someone give me some clue what can be the problem? 
I will then investigate it further, and can give code samples.
`                                                           
* com.example.app.activity.MapsActivity has leaked:                                                                 
* GC ROOT android.database.ContentObserver$Transport.mContentObserver                                                       
* references com.squareup.sqlbrite.BriteContentResolver$2$1.this$1 (anonymous subclass of android.database.ContentObserver) 
* references com.squareup.sqlbrite.BriteContentResolver$2.this$0 (anonymous implementation of rx.Observable$OnSubscribe)    
* references com.squareup.sqlbrite.BriteContentResolver.contentResolver                                                     
* references android.app.ContextImpl$ApplicationContentResolver.mContext                                                    
* references android.app.ContextImpl.mOuterContext                                                                          
* leaks com.example.app.activity.MapsActivity instance                                                              
* Retaining: 694 KB.                                                                                                        
* Reference Key: 5bd66348-2f45-4eda-8fd5-f6e7032155c7                                                                       
* Device: HTC htc HTC Desire 620 a31ul_tmo_pl                                                                               
* Android Version: 4.4.4 API: 19 LeakCanary: 1.5.1 1be44b3                                                                  
* Durations: watch=9238ms, gc=158ms, heap dump=1062ms, analysis=51689ms                                                     `

**Comment by JakeWharton** [comment]
You're not unsubscribing from the returned `Observable` at the appropriate lifecycle event. Make sure you track subscriptions and unsubscribe when the UI is disappearing.
