### ISSUE TITLE
Provide helpers for more type-safe querying (or at least less stringy)

### ISSUE THREAD

**Issue by JakeWharton** [square/sqlbrite#2]
String concatenation is arduous and error-prone. Provide a means of constructing queries in a way that reduces errors, increases type-safety, and isn't extremely noisy in the code.

**Comment by alexfu** [comment]
I've currently started working on a project whose sole purpose is to construct SQLite statements. Granted, this project is still in it's early infancy (and the addition of new features has been on an as needed basis at this point), it may be of interest to you for this case... https://github.com/alexfu/SQLiteQueryBuilder

**Comment by chalup** [comment]
I'm co-author of library which implements a fluent(ish) API for sqlite querying. The code is not pretty and there are some mutability issues, but it still beats the string concatenation:

https://github.com/futuresimple/android-db-commons/tree/master/library/src/main/java/com/getbase/android/db/fluentsqlite

**Comment by fourlastor** [comment]
@JakeWharton maybe a step ahead could be the possibility to pass something like this?

```java
Observable<Query> createQuery(/**list/string**/ tables, Func1<SQLiteDatabase, Cursor> func);
```

so that it would be easier to integrate with other existing solutions?

**Comment by JakeWharton** [comment]
Our solution to this is https://github.com/square/sqldelight and efforts around type-safe queries will be focused there.
