### ISSUE TITLE
What's new in 2.0?

### ISSUE THREAD

**Issue by eliasbagley** [square/sqlbrite#205]
Hey - I noticed that 2.0.0 was release a few days ago. Nice work!

Does 2.0 change/break anything, or is it just updating to RxJava 2.0? If so, I think it would be useful to have a section in the readme which briefly summarizes the changes.

**Comment by JakeWharton** [comment]
There's a change log which does this: https://github.com/square/sqlbrite/blob/master/CHANGELOG.md#version-200-2017-07-07

Do you have specific questions?

**Comment by eliasbagley** [comment]
Change log works for me. Thanks.
