### ISSUE TITLE
Does brite database support update or insert method ?

### ISSUE THREAD

**Issue by Kritartha** [square/sqlbrite#206]
If a row with a particular primary key is not present then it should create a new row like other DBs. Is there any method to execute this ?

**Comment by JakeWharton** [comment]
This question is not specific to SQL Brite. Please ask general Android DB usage questions on StackOverflow. You can use the `CONFLICT_REPLACE` strategy on your insert for this behavior.

**Comment by Kritartha** [comment]
Alright. Thanks Jake.
