### ISSUE TITLE
Is using Schedulers.io() a mistake for initializing sqlbrite?

### ISSUE THREAD

**Issue by schristmann** [square/sqlbrite#208]
I'm getting hit with the ensureNotInTransaction exception at random on a simple query that I know is run close to the same time as a lot of web service loading and caching. My best guess is this exception triggers if a web service call happens to be caching data at the same time a query starts, which is a reasonable occurrence anywhere in my app. I have to assume this is because Schedulers.io() works from a thread pool. However the presence of this exception tells me that sqlbrite wants to be single threaded, so is Schedulers.io() really bad to init with? What other guarantee can i use to protect against this exception happening, other then dropping to a single threaded scheduler?

**Comment by JakeWharton** [comment]
`Schedulers.io()` is fine as it's just a thread pool. The only way this would trigger is if you potentially leaked a transaction.

Without a sample or something it's going to be impossible to know what's going on.

**Comment by schristmann** [comment]
Sorry I think I jumped the gun on this one. I didn't realize that transactions were stored in a ThreadLocal value. My first pass lead me to think that if Thread A was in the middle of a transaction, that if Thread B started a query it would trigger this exception, but it seems that shouldn't be the case.

You are probably right then that one of the transactions isn't completing somewhere in our code.

**Comment by JakeWharton** [comment]
Yeah our use of ThreadLocal mirrors the SQLite APIs of Android's use of
them as well to track connections.
