### ISSUE TITLE
Does it support the encrypted SQLite?

### ISSUE THREAD

**Issue by nishant-neosoft** [square/sqlbrite#219]

**Comment by zikil** [comment]
@nishant-neosoft From the project description: 

> A lightweight wrapper around SQLiteOpenHelper and ContentResolver which introduces reactive stream semantics to queries.

It does not provide any additional functionality for your database. It is just a wrapper. If you want to have encrypted sql database, use SqlCipher or any other implementation and wrap it with SqlBrite to be more reactive.

**Comment by JakeWharton** [comment]
And the code on `master` which will be 3.0 when released supports the Android support library SQLite abstraction allowing you plug in any API compliant DB.
