### ISSUE TITLE
Robolectric support?

### ISSUE THREAD

**Issue by ZakTaccardi** [square/sqlbrite#22]
Is it just me, or does SqlBrite not work with Robolectric?

**Comment by JakeWharton** [comment]
If that was the case it would be Robolectric's bug.

The library consists only of usage of the platform's Sqlite APIs and RxJava. Robolectric embeds a SQL version that's compiled for the desktop and does not strictly match the behavior of Android's. RxJava is just a Java library so it'll work anywhere.

You also haven't described how it's failing, what errors you're seeing, how you are using it, etc.

You might want to try StackOverflow, the Robolectric mailing list, or the Robolectric issue tracker. Unless there's a specific, reproducible problem with SqlBrite I don't think there's any action to take for us.
