### ISSUE TITLE
Can't import FrameworkSQLiteOpenHelperFactory

### ISSUE THREAD

**Issue by xxia34** [square/sqlbrite#223]
I've imported sqlbrite 3.0 and I'm trying to use it based on the sample code given. However android studio can't find FrameworkSQLiteOpenHelperFactory specifically. Is there something else I should be importing?

https://github.com/square/sqlbrite/blob/9de0c83830413bbc05734ebd15da8c587ffd23ff/sample/src/main/java/com/example/sqlbrite/todo/db/DbModule.java

**Comment by JakeWharton** [comment]
Do you have a dependency on the `db-framework` artifact?

**Comment by JakeWharton** [comment]
See here: https://github.com/square/sqlbrite/blob/9de0c83830413bbc05734ebd15da8c587ffd23ff/sample/build.gradle#L22
whose variable is: https://github.com/square/sqlbrite/blob/d6ae8b549330a298cbb9d0a3a59a402591e3f013/build.gradle#L37

**Comment by xxia34** [comment]
Thanks! I had tried 'com.android.arch.persistence:db-framework:1.0.0'  instead of 'android.arch.persistence:db-framework:1.0.0'
