### ISSUE TITLE
Support for unit testing surrounding code is missing or undocumented

### ISSUE THREAD

**Issue by randallmitchell** [square/sqlbrite#228]
BriteDatabase is final and therefore cannot be mocked.  For me, this means code that using SqlBrite's database functionality cannot be unit tested by graceful means.  Is there any existing mechanism or intention for this library to support unit testing?

If there is an existing mechanism to support unit testing, it maybe needs documentation and I'd be happy to contribute that documentation.

In the interim, putting a light wrapper around the database may be a viable workaround.  I'm working on proofing that out in sample code and can report my findings here... though QueryObservable is also final... potentially compounding the problem or making the potential workaround non-viable.

**Comment by JakeWharton** [comment]
There is no need to mock BriteDatabase. If you're testing queries and mapping you can use an in-memory DB by supplying `null` as the filename. If you want to fake the mapped values (e.g., `List<Foo>`) then you should have a higher-level of abstraction like a "store" or "repository" that you can mock/fake.

BriteDatabase operates at a level of abstraction that is unsuitable for mocking, as your tests would become tied to the consuming code. Every change in how you query would require a change in how you mock which is a strong indicator that you're mocking something not meant to be mocked.

**Comment by randallmitchell** [comment]
I missed the open helper feature for in-memory databases.  Thanks you.

I'm actually working on writing tests for my repository.  I typically prefer to pass in a mocked persistence layer to my repositories.  I will evaluate this pattern against your point about tying tests to query implementation.  It has cause some pain.  Thanks again.

**Comment by artem-zinnatullin** [comment]
Another option could be Robolectric, which will provide JVM-compatible
implementation of SQLiteOpenHelper with actual SQLite under the hood.

But, of course Robolectric is very questionable answer to "unit" testing.

// And of course it's possible to mock SQLiteOpenHelper and delegate calls
to manually JNI-linked SQLite if you don't want to use Robolectric.

**Comment by JakeWharton** [comment]
I have a hard time recommending Robolectric for anything serious as the
Sqlite it uses is built for the JVM and lacks the ICU support that Android
provides. This means if you're using anything like collation you'll get
different results. That being said, it's always better than mocking. You
should never mock queries against the DB. Your tests won't actually be
tests, they'll just be scripts to appease your implementation.
