### ISSUE TITLE
The problem of  an existed db

### ISSUE THREAD

**Issue by liuyasss** [square/sqlbrite#236]
how to do ,open an existed db from assets dir,  I cannot find the method

so ,I want to request to you， please ，thank you

Android

**Comment by liuyasss** [comment]
I find the `openOrCreateDatabase` in the SQLiteDatabase,but I real not find a similar methond，

please ， can you give me some advising，thank you

**Comment by JakeWharton** [comment]
SQL Brite doesn't change what happens when you want to pre-pack a DB file in your assets directory. You need to copy it into the correct location before creating the SQLiteOpenHelper and then wrapping it in SQL Brite.

**Comment by liuyasss** [comment]
thank you

谢谢



发自我的小米手机
在 Jake Wharton <notifications@github.com>，2018年1月28日 03:55写道：

SQL Brite doesn't change what happens when you want to pre-pack a DB file in your assets directory. You need to copy it into the correct location before creating the SQLiteOpenHelper and then wrapping it in SQL Brite.
