### ISSUE TITLE
Want to use insertWithOnConflict with SQLBrite

### ISSUE THREAD

**Issue by rafaelekol** [square/sqlbrite#24]
I use transactions to insert multiple items via SQLBrite wrapper. Problem is that some items can be already in database, so there are conflicts. I want to use insertWithOnConflict() method with IGNORE for conflicts. How I can accomplish this using SQLBrite?
```java
    sqlBrite.beginTransaction();
            try {
                for (Message msg : messages) {
                    insertMessageViaSQLBrite(msg);
                }
                sqlBrite.setTransactionSuccessful();
            } finally {
                sqlBrite.endTransaction();
            }
```

**Comment by tomxor** [comment]
Use this: https://github.com/square/sqlbrite/blob/master/sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java#L346-L368

**Comment by rafaelekol** [comment]
Thank you, that did the job
