### ISSUE TITLE
[Q] How to implement memory cache if i using  BriteDatabase.createQuery()?

### ISSUE THREAD

**Issue by Guang1234567** [square/sqlbrite#240]
Hello dev:

How to implement memory cache if using  `BriteDatabase.createQuery`? Could you give me some suggestion?

My code is below, but it does not working (I using [cancat operator](http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/))

```java

public class MainRepository implements MainDataSource {

    private final ListsItemDao mListsItemDao;

    @VisibleForTesting
    @Nullable
    Map<Long, ListsItem> mCachedListsItems;

    @Inject
    public MainRepository(ListsItemDao listsItemDao) {
        mListsItemDao = listsItemDao;
        mCachedListsItems = new HashMap<>();
    }

    @Override
    public Observable<List<ListsItem>> createQueryListsItems(final long max) {
        Observable<List<ListsItem>> disk =  mListsItemDao.createQueryListsItems(max) // 省内存
                .doOnNext(new Consumer<List<ListsItem>>() {
                    @Override
                    public void accept(List<ListsItem> listsItems) throws Exception {
                        mCachedListsItems.clear();
                        Iterator<ListsItem> it = listsItems.iterator();
                        while (it.hasNext()) {
                            ListsItem listsItem = it.next();
                            mCachedListsItems.put(listsItem.id(), listsItem);
                        }
                    }
                });

        Observable<List<ListsItem>> memory = Observable.create(new ObservableOnSubscribe<List<ListsItem>>() {
            @Override
            public void subscribe(ObservableEmitter<List<ListsItem>> e) throws Exception {
                    e.onNext(new ArrayList<ListsItem>(mCachedListsItems.values()));
            }
        });

        return Observable.concat(memory, disk).firstOrError().toObservable();
    }
}

```

In addition, `MainRepository.createQueryListsItems(100L)` must receive change event after Database was modified by  `BriteDatabase.insert(...)`

**Comment by shaishavgandhi05** [comment]
`firstOrError()` returns a `Single` which means it will only emit one item. Converting it to an Observable with `toObservable()` will not convert it into a "hot" observable. If you want changes on database to propagate to your View layer and want a memory cache, you could look for something like `PublishSubject` or `PublishRelay` which is both an Observer and Observable. i.e it can listen to changes in database, store them in cache and relay them on to the View layer. 

This doesn't seem to be a SQLBrite related question

**Comment by JakeWharton** [comment]
I would recommend using https://github.com/JakeWharton/RxReplayingShare which will share the latest value to any new subscriber synchronously and then attach to the existing query for future updates.

**Comment by Guang1234567** [comment]
@shaishavgandhi05  
@JakeWharton

Thank you for your valuable advice.

**Comment by Guang1234567** [comment]
@JakeWharton 

Althought using [RxReplayingShare](https://github.com/JakeWharton/RxReplayingShare), but 

`Query.run()` everytime after rotate the display because `startWith` operator in

https://github.com/square/sqlbrite/blob/e235fde6e2aa9c8813605dc73cead37c7dd9f3f2/sqlbrite/src/main/java/com/squareup/sqlbrite3/BriteDatabase.java#L386

Do you have any idea to avoid  this **redundant `Query.run()`** after rotate the display?

**Comment by JakeWharton** [comment]
No. It shouldn't matter because at worst it re-queries the cached
information and at best you get updated results.
