### ISSUE TITLE
Rollback instead of Replace

### ISSUE THREAD

**Issue by Shahroz16** [square/sqlbrite#245]
Whenever I call, 

`db.insert("table name", OnConflictStrategy.REPLACE, params)`

In the logs, I see

_D/SQL Database: INSERT
      table: //table name
      values: // params values
      conflictAlgorithm: rollback_

Is this, `conflictAlgorithm: rollback` intended?

**Comment by JakeWharton** [comment]
`OnConflictStrategy.REPLACE` comes from Room. You should be using `SQLiteDatabase.CONFLICT_REPLACE`.
