### ISSUE TITLE
SupportSqliteOpenHelper

### ISSUE THREAD

**Issue by ntoskrnl** [square/sqlbrite#246]
Room uses `SupportSqliteOpenHelper` (which is just an abstraction for SqliteOpenHelper).

When migrating from sqlbrite to room it would be nice to support new `SupportSqliteOpenHelper`, as in `sqlBrite.wrapDatabaseHelper(myRoomDatabase.getOpenHelper())`

**Comment by JakeWharton** [comment]
The SQLite support library abstraction was used since version 3.0.

**Comment by ntoskrnl** [comment]
Oh, yes, I haven't noticed that our project is still on 2.0.0
