### ISSUE TITLE
I hope this is updated with the sqlite support library of androidx 

### ISSUE THREAD

**Issue by brownsoo** [square/sqlbrite#252]
3.2 version works OK. but I hope this is updated with the sqlite support library of androidx.

**Comment by JakeWharton** [comment]
Is jetifier not sufficient?

**Comment by brownsoo** [comment]
Yes. Jetifier is sufficient. I mentioned this because just hinting the type mismatch error in IDE. It's not required issue.


    import androidx.sqlite.db.SupportSQLiteDatabase
    import androidx.sqlite.db.SupportSQLiteOpenHelper
    import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
    ...
    private var brite: BriteDatabase? = null
    fun open() {
        // Type mismatch hinting in android studio IDE ----- //
        brite = sqlBrite().wrapDatabaseHelper(openHelper(context), Schedulers.io())  
    }
    private fun openHelper(context: Context): SupportSQLiteOpenHelper {
        val configuration = SupportSQLiteOpenHelper.Configuration.builder(context)
            .name(DB_NAME)
            .callback(DBCallback(DB_VERSION))
            .build()
        return FrameworkSQLiteOpenHelperFactory().create(configuration)
    }

**Comment by JakeWharton** [comment]
Did you invalidate caches and restart? Running jetifier is pretty damaging in terms of the IDE's cache and resetting it tends to fix these issues.

**Comment by brownsoo** [comment]
Gooood!! Thank ~~! You are the best!!
