### ISSUE TITLE
Invalidate a query manually.

### ISSUE THREAD

**Issue by xMikeTx** [square/sqlbrite#28]
Quick question:
Is there a way to run a query of an observable manually.

e.g. I have an active subscription for an observable which listens to changes of table A. In my observable the result of the query is modified, so I only have a subset of the queried rows. 
This step depends on a parameter that can change randomly and is not in the database, so I need to tell the query to run again once that parameter changes.
Something like notifyDataSetChanged();

Am I doing something weird here? 

Currently I just create a new observable with a subscription once the parameter changes, which doesn't feel right.

**Comment by JakeWharton** [comment]
There's a few ways to do this...

Is the parameter you mentioned able to be modeled as an observable?
```java
Observable<String> theParam = observeParam().distinctUntilChanged();

theParam.flatMap(param -> dbQuery(param)).subscribe(dbResults);
```
This assumes that subscribing to the observable returned from `observeParam()` sends out the initial value right away. Maybe it only broadcasts changes and then you could do:
```java
Observable<String> theParam = paramChanges().startWith(currentParamValue()).distinctUntilChanged();
```

Another thing to note is that the `Query` object from SqlBite can have its `.run()` method called multiple times. This means you could do `combineLatest` and use the `param` to run the query again.

```java
Observable<String> theParam = observeParam();
Observable<Query> theQuery = createQuery();
Observable.combineLatest(theParam, theQuery, someFunction)
    .subscribe(Pair<String, Query> pair -> doSomething(pair.first, pair.second);
```

Finally, if the param isn't an observable you can use a `PublishSubject<String>` with one of the above techniques and just call `subject.onNext(newParam)` when the parameter changes.

Hope that helps! Let me know if you have any follow-ups.

**Comment by xMikeTx** [comment]
Perfect. Thanks for your awesome code.
