### ISSUE TITLE
Notify when updates are made in a different process

### ISSUE THREAD

**Issue by xMikeTx** [square/sqlbrite#29]
My Setup:
- App that listens to database changes via Loader and updates the UI accordingly
- SyncAdapter, that fills the data via contentenprovider but in a different :sync process.

I wanted to replace the ContentProvider and Loader stuff with SQLBrite. It works fine, but I do not receive the database updates made in the :sync process. I suppose SQLBrite cannot handle this right now? 

As a workaround I was thinking about delivering the updates via broadcasts, and call an update in my app process. This seems however like a messy solution, so I was wondering if 
a.) SQLBrite does support those inter process  update notifications, and I just didn't get it.
b.) A cleaner way to deliver those database update notifications to the app process.

hope, somebody has an idea.

best, MikeT.

**Comment by artem-zinnatullin** [comment]
You can use ContentProvider with ContentResolver via SqlBrite (I'm not sure
about class name, please check the repository) and have inter process for
free.
8 июня 2015 г. 12:13 PM пользователь "xMikeTx" <notifications@github.com>
написал:

**Comment by xMikeTx** [comment]
Thanks for that info, sorry I missed that. 
This looks like exactly what I need.

This change is  not in the official release yet, so I will checkout the SNAPSHOT version.

**Comment by artem-zinnatullin** [comment]
Great, I think you can close this issue now :)
8 июня 2015 г. 2:15 PM пользователь "xMikeTx" <notifications@github.com>
написал:

**Comment by xMikeTx** [comment]
So I investigated the solution, but unfortunately it is not quite what I wanted.

While the SqlBriteContentProvider works if I simply want to replace my current contentprovider stuff, but I have to check if there is also an easy way to update all my SQLBrite raw queries.

But I think I got the idea, and will close the issue as soon as I figured it out.

**Comment by artem-zinnatullin** [comment]
There are no easy ways to use raw queries with `ContentProvider` just because you can use any storage under the hood of `ContentProvider`, not only `SQLite`, but you can create custom URIs for such purposes and process them as raw queries in your `ContentProvider`.

Or you can write custom solution with throwing broadcasts about changes in the db, catch them in other processes and trigger `onNext()` in the `SqlBrite`'s `PublishSubject`.

**Comment by xMikeTx** [comment]
Yes, I figured that much :(. Thank you for the explanation. 
I will try to create a clean solution with PublishSubject.

Thank you for your help
