### ISSUE TITLE
DAO layer

### ISSUE THREAD

**Issue by sockeqwe** [square/sqlbrite#32]
Hi, 
first of all, thanks for this great library.

I was wondering if you are still working on #2 and #1  because I have started my own approach by introducing a DAO layer: https://github.com/sockeqwe/sqlbrite-dao 
The idea is to have a DAO base class that already provides a SQL Builder like discussed in #2 with pure sql language support and additionally a little annotation processor to map the data from a cursor to real object. Please note that it is not a ORM nor provides it's own query language for resolving relations. The goal is to write pure sql queries (you don't have to learn another library specific query language) and reduce writing boilerplate code for iterating over a `Cursor` (this is done by annotation processing).

But before I put more effort into this project, I wanted to ask you if you already work on your own solution for that?

If you are interested in my solution:

There is a [DaoManger](https://github.com/sockeqwe/sqlbrite-dao/blob/master/dao/src/main/java/com/hannesdorfmann/sqlbrite/dao/DaoManager.java) which extends from `SQLiteOpenHelper` and kind of represents a database. Internally it instantiates `SqlBrite`instance which gets "injected" to the registered  DAOs. A [Dao](https://github.com/sockeqwe/sqlbrite-dao/blob/master/dao/src/main/java/com/hannesdorfmann/sqlbrite/dao/Dao.java)  represents a database table. 

```java
public class CustomerDao extends Dao {

  @Override public void createTable(SQLiteDatabase database) {
    CREATE_TABLE(
                 Customer.TABLE_NAME, 
                 Customer.COL_ID + " INTEGER PRIMARY KEY NOT NULL",
                 Customer.COL_FIRSTNAME + " TEXT", 
                 Customer.COL_LASTNAME + " TEXT")
    .execute(database);
  }

  @Override public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
  }

  public Observable<List<Customer>> getCustomers() {
    return query(

               SELECT(Customer.COL_ID, Customer.COL_FIRSTNAME, Customer.COL_LASTNAME)
               .FROM(Customer.TABLE_NAME)

           ).map(new Func1<SqlBrite.Query, List<Customer>>() {
                    @Override public List<Customer> call(SqlBrite.Query query) {

                          Cursor c = query.run();
                          List<Customer> customers = CustomerMapper.list(c); // Annotation Processing
                          return customers;

                      }
           });
  }

  public Observable<Long> insert(int id, String firstname, String lastname) {
  
    ContentValues values = new ContentValues();
    values.put(Customer.COL_ID, id);
    values.put(Customer.COL_FIRSTNAME, firstname);
    values.put(Customer.COL_LASTNAME, lastname);

    return insert(Customer.TABLE_NAME, values);
  }
}

```

To repeat my question: Do you work on or have plans to provide a first party solution by your own?

**Comment by sockeqwe** [comment]
By the way: Maybe the annotation processor based "ObjectMapper" could be of interest regarding #1

**Comment by JakeWharton** [comment]
Our solution to this is https://github.com/square/sqldelight and efforts around higher-level object mapping, migrations, etc. will be focused there.

**Comment by sockeqwe** [comment]
:+1:  
Awesome solution for that!
