### ISSUE TITLE
onCompleted has not been called

### ISSUE THREAD

**Issue by pablobaldez** [square/sqlbrite#36]
When I use createQuery with Subscriber as a observer, the onCompleted method isn't called. I think the process have been finished in onNext method.

**Comment by JakeWharton** [comment]
SqlBrite will never call `onComplete`. Streams always remain open so that changes to the data can be propagated to all subscribers. You must unsubscribe for a stream to stop or limit it in some other fashion such as `first()`, `take(n)`, or `takeUntil(otherObservable)`.

**Comment by pablobaldez** [comment]
if i call first() (or some method like this) the onCompleted should be called Or I should use this just to kill my stream?

I tried this approach but just the doOnComple defined on createQuery was called

**Comment by JakeWharton** [comment]
Yes, RxJava will call `onCompleted` after whatever condition you specify. In the case of `first()`, it's after the initial `Query` object is sent through the stream.

If you are using `doOnComplete`, it needs to be _after_ the `first()` / `take()` / `takeUntil()` call.

**Comment by pablobaldez** [comment]
This only works when i put first() after doOnComplete and after subscribeOn but now everything it's all right. Thank you
