### ISSUE TITLE
Support for rxAndroid 1.0.x

### ISSUE THREAD

**Issue by aastroem** [square/sqlbrite#40]
Is support for rxAndroid 1.0.x planned ? There is a lot of (breaking) changes between rxAndroid 0.25.0 and 1.0.1, so we're a bit reluctant to start a new project with the older version ... but then again sqlbrite seems to solve many of our problems

**Comment by artem-zinnatullin** [comment]
@aastroem SQLBrite does not depend on RxAndroid, you can use any version of RxAndroid with it.

**Comment by aastroem** [comment]
@artem-zinnatullin Thanks, looks like you're right :+1:  It's just the sqlbrite-sample module that depends on rxAndroid 0.25.0, but I guess that will be updated eventually
