### ISSUE TITLE
mapToOneOrDefault?

### ISSUE THREAD

**Issue by JakeWharton** [square/sqlbrite#55]
Instead of `mapToOneOrNull`.

**Comment by jparkie** [comment]
Why not both? In more functional languages, for monadic data structures, they often expose a `getOrElse` and an `orNull` like [http://www.scala-lang.org/api/2.11.7/index.html#scala.Option](http://www.scala-lang.org/api/2.11.7/index.html#scala.Option).

**Comment by JakeWharton** [comment]
I'm hoping that the use of `null` is more of a rarity than the norm in this case, and that those who actually want `null` can just pass it explicitly as a default. I realize that it's only one method and all it does is call another, but every method has a cost and unless there's a compelling reason to have both I always default to having only one.

**Comment by jparkie** [comment]
Understandable; Android DEX limits. :)
