### ISSUE TITLE
Add execSQL to BriteDatabase

### ISSUE THREAD

**Issue by gokhanbarisaker** [square/sqlbrite#57]
Motivation can be found at **Using a Prepared Statement** section of http://stackoverflow.com/q/1711631/892500

**Comment by gokhanbarisaker** [comment]
This is also preventing developers to create tables on the fly.

**Comment by JakeWharton** [comment]
You can create tables with the underlying `SQLiteOpenHelper`

**Comment by gokhanbarisaker** [comment]
SQLiteOpenHelper works perfectly for static tables. My goal with second comment is using database cache on infinite scroll within multiple activities. In order to achieve that, I need to create per Activity per Cache relationship. As far as I know sqlbrite does not provide any getter for wrapped SQLiteOpenHelper. Should I hold a reference for my helper on somewhere else? It would be awesome, if sqlbrite enable execSQL these APIs.

**Comment by serandel** [comment]
You could use the SQLiteOpenHelper, but I think it's more confusing, and you have to pass both the helper and the BriteDatabase around. 

+1 to this petition.

**Comment by AlecStrong** [comment]
I'd be cautious of adding anything as flexible as `execSql` to SqlBrite. We've avoided things like that because we want to have a straightforward mechanism for sending out triggers, and with `execSql` you could perform inserts, updates and deletes without us knowing. You can already do that with the underlying `SQLiteOpenHelper` but at least in that case you have to be more explicit with it and it's not our problem.

**Comment by artem-zinnatullin** [comment]
You can give users a getter for the underlying `SQLiteOpenHelper` so they could use any methods of the `SQLiteDabase` like `execSql()` without need in passing both helper and `BriteDabase` around.

**Comment by serandel** [comment]
But in some cases you just want to optimize a FTS table, or vacuum the DB. If you use execSQL for inserts and expect notifications... well, it's clear you're doing it wrong. :)

**Comment by JakeWharton** [comment]
Yeah. I think we'll probably add it with a strong warning.

**Comment by brucexia** [comment]
how can you do something like update status set progress=progress+1, without execSql?

**Comment by JakeWharton** [comment]
See my previous comment.

**Comment by brucexia** [comment]
@JakeWharton so is there a plan to add execSql so we get trigger? I'd be happy to contribute that featue

**Comment by JakeWharton** [comment]
There is a plan for execSql, but there's no way to support triggers without
forcing them to be manually specified (which isn't the end of the world).
