### ISSUE TITLE
Immediate notification for initial data should be optional for BriteContentResolver

### ISSUE THREAD

**Issue by djensen47** [square/sqlbrite#59]
For many situations getting the initial data is exactly what you want. However, there are other situations where you _only_ want to be notified when the content changed.

For instance, when an SMS is sent or received. I don't want an immediate notification for that because that SMS may have just been sent or sent a long time ago.

It seems the `startWith` operator is what provides this functionality

https://github.com/square/sqlbrite/blob/master/sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java#L105

For the time being I can use the `skip(1)` operator to ignore the first result cleanly. 

It would be nice if there were another API to skip the immediate notification…

```java
 public QueryObservable createQuery(
        @NonNull final Uri uri, 
        @Nullable final String[] projection,
        @Nullable final String selection, 
        @Nullable final String[] selectionArgs, 
        @Nullable final String sortOrder, 
        final boolean notifyForDescendents,
        boolean skipFirst)
```

The existing API could call this one with true passed in as the last argument.

**Comment by JakeWharton** [comment]
I don't see what this offers over `skip(1)`. We could put `skipInitial()` on `QueryObservable` which would just be a type-safe alias for `skip(1)`, but if you put an operator between the two then you'd lose the ability to use it (already a problem with `QueryObservable`, I'll note).

**Comment by djensen47** [comment]
True. 

Maybe all that needs to be "fixed" is an update in the documentation to indicate that one should use `skip(1)` if one does not want the immediate notification. I'm relatively new to RxJava but I'm also comfortable digging into the open source to see how it all works. Other's may not initially realize that `skip(1)` is an legitimate work-around.

**Comment by JakeWharton** [comment]
Yeah. At the very minimum that is what we should do.

In our code we usually put `skip(1) // Ignore initial value.` to further indicate the intention.

**Comment by djensen47** [comment]
:+1:
