### ISSUE TITLE
OnCompleted called when unsusbsribed & swallowed exceptions

### ISSUE THREAD

**Issue by Lakedaemon** [square/sqlbrite#64]
I had a glimpse at the asRows method of the Query abstract class 
and it looks to me like : 

exceptions are swallowed (no onError calls)
onCompleted gets called even if the observable has been unsubscribed.

This feels weird... Or am I wrong ?

**Comment by JakeWharton** [comment]
Exceptions are automatically propagated.
```java
Observable.create(subscriber -> {
  throw new RuntimeException("Broken");
}).subscribe(System.out::println, throwable -> {
  throwable.printStackTrace(System.out);
});
```
Prints to stdout:
```
java.lang.RuntimeException: Broken
	at Main.lambda$main$0(Main.java:6)
	at Main$$Lambda$1/20132171.call(Unknown Source)
	at rx.Observable.subscribe(Observable.java:7804)
	at rx.Observable.subscribe(Observable.java:7772)
	at rx.Observable.subscribe(Observable.java:7574)
	at Main.main(Main.java:7)
```

Feel free to send a PR for wrapping the `onCompleted` in an unsubscribed check.

**Comment by Lakedaemon** [comment]
Yes, you are right. Silly me.

**Comment by JakeWharton** [comment]
Thanks for the report and the fix!
