### ISSUE TITLE
Typesafe `skip()` / `take()` `QueryObservable`

### ISSUE THREAD

**Issue by chrisjenx** [square/sqlbrite#69]
This would open a rabbit hole of Rx calls on the `QueryObservable`. But trying to `take(1)` one `Query` or `skip(1)` is a bit of a pain at the moment.

Doing something like `take(1).mapToOne()` would be really handy. But not sure where you would draw the line at which methods to override.

I guess an alternative for `take(1).mapToOne()` would be to enable a `query(String query, String... args)` where no table is passed indicating you just want to run the query once and not observe the table.

**Comment by JakeWharton** [comment]
Both of these methods are `final` so they cannot be overridden. You can invert the order in which they're called: `mapToOne().take(1)` and `mapToOne().skip(1)`. Unfortunately in the latter case it waste an allocation doing the map only to just drop it. The `take` case is exactly the same though.

**Comment by chrisjenx** [comment]
Well the problem with the former `mapToOne().take(1)` case, is that if the row does not exist nothing emitted then it will wait indefinitely (or at least until that row actually exists).

In some cases we want to do: `mapToOne().take(1).switchOnEmpty(createFooBar())`.

**Comment by chrisjenx** [comment]
So to get around the _zero results_ issue I have been doing something like this:

```
.mapToOneOrDefault(Mappers.CAMERA_FEATURE, null)
.first()
.flatMap(cameraFeature -> {
      if (cameraFeature == null) {
            return //do something else
      } 
      return Observable.just(cameraFeature);
})
```

**Comment by JakeWharton** [comment]
Got it. Have some ideas to play with tonight or tomorrow.
