### ISSUE TITLE
Replace BackpressureBufferLastOperator with onBackpressureLatest in RxJava 1.1

### ISSUE THREAD

**Issue by JakeWharton** [square/sqlbrite#73]
When RxJava 1.1 is released and we update to support it, remove the custom `BackpressureBufferLastOperator` class in favor of the native `onBackpressureLatest()` operator.

**Comment by akarnokd** [comment]
`BackpressureBufferLastOperator` looks a bit odd to me and its current implementation doesn't match `BackpressureBufferLastOperator`. 

In your operator, you keep reemitting the last value in case one requests repeatedly. If I go 1 by 1 via a `filter()`, if the last value doesn't match a filter, we have a tight loop with possible stackoverflow as the producer doesn't seem to be reentrant-safe.

In addition, `onNext` emissions towards the child may race with a request from downstream and yielding concurrent `onNext` calls.

**Comment by JakeWharton** [comment]
The values emitted are always the same exact instance and they're stateless
factories with no exposed pieces of data. So yes, in theory that could
happen, but it's unlikely in practice as the objects don't even have
anything to filter against.

I never even thought of that potential behavior though. Knowing that the
same instance would always be emitted is what led to shortcuts being taken
in the operator, but I guess we also introduced some potential bugs as well.
