### ISSUE TITLE
onUpgrade

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/sqlbrite#74]
Hi,
I see in your DbOpenHelper, you overrode the `onUpgrade()` method.  However, you aren't handling this use case.  I am wondering if it would be prudent to have something like this:
`db.execSQL("DROP TABLE IF EXISTS " + TodoList.TABLE);   
onCreate(db);
`

Thanks,
Igor

**Comment by JakeWharton** [comment]
That would eliminate all the user's data. The sample app has only one DB version, so nothing needs to be in onUpgrade because it will never run. If we ever change the schema for some reason, we'll add proper migrations.

Also it's just a sample app and writing a proper open helper isn't the focus.
