### ISSUE TITLE
Question about a testcase

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/sqlbrite#75]
Hi,
in your BriteDatabaseTest, you have a `transactionCreatedFromTransactionNotificationWorks()`.  It says that it
> // Tests the case where a transaction is created in the subscriber to a query which gets
    // notified as the result of another transaction being committed.

Here is the full code:

`@Test public void transactionCreatedFromTransactionNotificationWorks() {`
    // Tests the case where a transaction is created in the subscriber to a query which gets
    // notified as the result of another transaction being committed. With improper ordering, this
    // can result in creating a new transaction before the old is committed on the underlying DB.

    db.createQuery(TABLE_EMPLOYEE, SELECT_EMPLOYEES)
        .subscribe(new Action1<Query>() {
          @Override public void call(Query query) {
            db.newTransaction().end();
          }
        });

    Transaction transaction = db.newTransaction();
    try {
      db.insert(TABLE_EMPLOYEE, employee("john", "John Johnson"));
      transaction.markSuccessful();
    } finally {
      transaction.end();
    }
  }

My question is - where does one transaction notify the other transaction here?  I am not seeing it...

Thanks,
Igor

**Comment by JakeWharton** [comment]
`end()` previously triggered query notification before closing the transaction on the underlying DB. If you revert [the change][1] that was made in the commit that introduced the test case you will see it fail.

 [1]: https://github.com/square/sqlbrite/commit/7a68a06816c09f528cf733c81ee40c8e65207e5b

**Comment by IgorGanapolsky** [comment]
Gracias for the good testing examples.  @JakeWharton @changetip $1.

**Comment by changetip** [comment]
Hi @jakewharton, @IgorGanapolsky sent you a tip worth 3,047 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/920611)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
