### ISSUE TITLE
How to close cursor in mapToList()?

### ISSUE THREAD

**Issue by KChernenko** [square/sqlbrite#94]
Hi, thanks for the library.

I was wondering how could I close cursor if I'm using mapToList() operator?
For example, I have a method:

```
public Observable<List<FilmModel>> getFilms() {
        return mDb.createQuery(DBContract.FilmsTable.TABLE_NAME,
                "SELECT * FROM " + DBContract.FilmsTable.TABLE_NAME)
                .mapToList(new Func1<Cursor, FilmModel>() {
                    @Override
                    public FilmModel call(Cursor cursor) {
                        return DBContract.FilmsTable.parseCursor(cursor);
                    }
                });
    }
```
Does SQLBite provide any api for closing cursor in this case? Like finallyDo() operator or something like that.

**Comment by AlecStrong** [comment]
The cursor is closed for you as part of the `mapToList` command. `mapToList` iterates through the cursor and calls your mapper on each row, then closes it after all mapping is complete.

**Comment by KChernenko** [comment]
@AlecStrong great! Thanks for the answer.
