### ISSUE TITLE
Provide a way to detect if currently in a transaction or not

### ISSUE THREAD

**Issue by adelnizamutdinov** [square/sqlbrite#96]
I would like to have some compile-time or runtime checks about whether or not the current thread is in the transaction

the easiest way - to expose the thread-local transaction and do runtime checks on it

the safest way I think would be to add insert/update/delete methods to the `Transaction` type
or just serving the `BriteDatabase` from the `Transaction`
otherwise it's kind of awkward to carry around both `BriteDatabase` type for modification methods and a `Transaction` type for a proof of transaction

what do you think?

**Comment by JakeWharton** [comment]
What goal are you trying to solve with this? What are you going to do with this information?

**Comment by adelnizamutdinov** [comment]
Here's my example

```kotlin
fun BriteDatabase.insertUser(cvs: ContentValues, user: User): Long =
    insert(Tables.USERS, fillUser(cvs, user), SQLiteDatabase.CONFLICT_REPLACE)

fun BriteDatabase.insertUsers(cvs: ContentValues, users: List<User>): Unit =
    users.forEachByIndex { u -> insertUser(cvs, u) }

fun BriteDatabase.insertMessages(cv: ContentValues, users: List<User>, messages: DialogMessages) {
  insertUsers(cv, users)
  messages.items.forEachByIndex { msg ->
    val dialogId = insertDialog(cv, msg)
    insertMessage(cv, dialogId, msg)
  }
}

fun insertHistory(hist: LongPollHistory): Unit =
    inTransaction {
      val cv = ContentValues()
      val messages = hist.messages
      val users = hist.profiles
      insertMessages(cv, users, messages)
      applyUpdates(hist.history, cv)
    }
```

for a single user insert I don't require a transaction
for a batch user insert I need a transaction
then that batch user insert is used in an insertion of both users and messages (which is used in a couple more places)
then that batch users + messages insert is used in a server history sync method, which is responsible for spawning the transaction

So here first function should work both with and without a transaction, 2 intermediate functions should only work in a transaction, and the function that spawns a transaction should not be in a transaction itself

Passing around a `Transaction` type would perfectly solve my problem, but I can't insert/update/delete with it, I also need a  `BriteDatabase`

I could carry around a both of them in a single type, but I see that as an unnecessary allocation

**Comment by adelnizamutdinov** [comment]
You know, while thinking about this problem I came up with this data type:

```kotlin
class BatchModification(val database: BriteDatabase,
                        val transaction: BriteDatabase.Transaction,
                        val values: ContentValues)
```

which gives me the access to all the modification methods, a proof of a transaction and a `ContentValues` that I can reuse :smiley:

**Comment by JakeWharton** [comment]
I think adding the i/u/d methods to `Transaction` is probably the easiest way forward here.

**Comment by adelnizamutdinov** [comment]
Thanks, I'll be thinking about that since you don't mind adding those to `Transaction`
